name: deploy on push
on: [push]

job:
  deploy-app:
    runs-on: ubuntu-lastest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.HOST}}
          username: ${{secrets.SHH_USER_NAME}}
          port: ${{secrets.SHH_PORT}}
          key: ${{secrets.SHH_KEY}}
          source: "./html/*"
          target: "/var/www/html"
          strip_component: 1
